# clear workspace
rm(list=ls())
options(stringsAsFactors=FALSE)
graphics.off()

# load libraries
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(arm)

## set working directory
setwd("C:/Users/Wayne/Documents/GitHub/ufo/analyses/input")
d<- read.csv("ufosightings.csv", header = TRUE)
View(d)

d$UK<- grepl("uk", d$city)
d$country<- ifelse(d$UK==TRUE, "gb", d$country)
d$canada<- grepl("canada", d$city)
d$country<- ifelse(d$canada==TRUE, "ca", d$country)
d$NZ<- grepl("zealand", d$city)
d$country<- ifelse(d$NZ==TRUE, "nz", d$country)
d$Ireland<- grepl("ireland", d$city)
d$France<- grepl("france", d$city)
d$Spain<- grepl("spain", d$city)
d$Germany<- grepl("germany", d$city)
d$Australia<- grepl("australia", d$city)
d$Japan<- grepl("japan", d$city)
d$China<- grepl("china", d$city)
d$India<- grepl("india", d$city)
d$Mexico<- grepl("mexico", d$city)
d$Austria<- grepl("austria", d$city)
d$Malaysia<-grepl("malaysia", d$city)
d$Jamaica<- grepl("jamaica", d$city)
d$Iceland<- grepl("iceland", d$city)
d$Vietnam<- grepl("viet", d$city)
d$Greece<- grepl("greece", d$city)
d$Pakistan<-grepl("pak", d$city)
d$Panama<- grepl("panama", d$city)
d$country<- ifelse(d$Ireland==TRUE, "ie", d$country)
d$country<- ifelse(d$France==TRUE, "fr", d$country)
d$country<- ifelse(d$Spain==TRUE, "sp", d$country)
d$country<- ifelse(d$Germany==TRUE, "gy", d$country)
d$country<- ifelse(d$Australia==TRUE, "au", d$country)
d$country<- ifelse(d$Japan==TRUE, "jp", d$country)
d$country<- ifelse(d$China==TRUE, "ch", d$country)
d$country<- ifelse(d$India==TRUE, "in", d$country)
d$country<- ifelse(d$Mexico==TRUE, "mx", d$country)
d$country<- ifelse(d$Austria==TRUE, "aa", d$country)
d$country<- ifelse(d$Malaysia==TRUE, "my", d$country)
d$country<- ifelse(d$Jamaica==TRUE, "ja", d$country)
d$country<- ifelse(d$Iceland==TRUE, "ic", d$country)
d$country<- ifelse(d$Vietnam==TRUE, "vm", d$country)
d$country<- ifelse(d$Greece==TRUE, "gr", d$country)
d$country<- ifelse(d$Pakistan==TRUE, "pk", d$country)
d$country<- ifelse(d$Panama==TRUE, "pm", d$country)
is.na(d$state.province)
unique(d$state.province)
d$State<- grepl("", d$state.province)
d$State<- ifelse(d$state.province=="", "us", d$State)
d$country<- ifelse(d$State==TRUE, "us", d$country)
unique(d$country)
unique(d$UFO_shape)
